services:
  - type: web
    name: agrofrut
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        sync: false   # você cola o valor manualmente no painel do Render
